version: "3"

services:

  backend:
    user: $UID:$GID
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./
        target: /opt/app/
    