name: build-docs

on:
  push:
    branches:
      - main

jobs:
  backend-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Python SetUp
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./backend/requirements.txt
        pip install -r ./backend/docs/sphinx/requirements.txt

    - name: Build (backend) Doc
      run: |
        cd backend/docs/sphinx
        make clean
        make html
        touch build/html/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: backend/docs/sphinx/build/html/
        target-folder: backend/
  frontend-doc:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Python SetUp
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: oncodash-app
    - name: Install typedoc
      run: |
        npm install -g typedoc
        npm install @open-wc/create

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./oncodash-app/docs/sphinx-js/requirements.txt

    - name: Build (frontend) Doc
      run: |
        cd oncodash-app/docs/sphinx-js
        make clean
        make html
        touch build/html/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: oncodash-app/docs/sphinx-js/build/html/
        target-folder: frontend/
