name: Release Workflow

on:
  release:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'


jobs:
  conventional-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
