name: Docker Build & Push Workflow
on:
  push:
      branches:
        - main

jobs:
  docker-buildnpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the docker-compose Stack
        run: docker-compose build

      - name: Push Docker Images
        run: docker-compose push



